services:
  barracks_lawyer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8507:8507"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GRADIO_ANALYTICS_ENABLED=False
      - GRADIO_SERVER_PORT=8507
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_ANALYTICS_ENABLED=False
